name: MLG
version: '${project.version}'
main: com.spaceniklas.mlg.Mlg
api-version: 1.16
authors: [ SpaceNiklas ]
description: MLG is a plugin that allows you to practice MLG's!
website: www.spaceniklas.com
commands:
  mlg:

